### ISSUE TITLE
Melhorar os testes do método parse do CNPJ

### ISSUE THREAD

**Issue by camilamaia** [brazilian-utils/python#106]
Ao invés de chamar os mesmos asserts do sieve, verificar se o método sieve foi chamado.

Ideia Análoga: https://github.com/brazilian-utils/brutils-python/blob/c741843e970f26f1ace3a3dedde7b2d5dfd11fee/tests/test_cpf.py#L35-L39

**Comment by antoniamaia** [comment]
posso fazer essa issue? ✋🏼
