### ISSUE TITLE
Renomear métodos parse para algum nome que seja mais explícito

### ISSUE THREAD

**Issue by camilamaia** [brazilian-utils/python#110]
Talvez "remove_symbols", "remove_symbols_cpf" e "remove_symbols_cnpj"?

**Comment by antoniamaia** [comment]
posso fazer essa? 😄

**Comment by camilamaia** [comment]
@antoniamaia Aparentemente o `closes #` só funciona quando tá escrito na descrição do PR, porque ele não fechou sozinho 😢 parece que não funfa se for só nos comentários.

Vou fechar manualmente aqui então, beleza?
