### ISSUE TITLE
Melhorar format_cnpj e o seus testes

### ISSUE THREAD

**Issue by camilamaia** [brazilian-utils/python#115]
1. Chamar a função `is_valid` e formatar o cnpj, sem utilizar o método display.
Código referência:
https://github.com/brazilian-utils/brutils-python/blob/756f1267b78ed597a7b65fd344a8ae2c6bf6a0b9/brutils/cpf.py#L38-L48

2. Melhorar os testes da função format_cnpj:

Código referência:
https://github.com/brazilian-utils/brutils-python/blob/756f1267b78ed597a7b65fd344a8ae2c6bf6a0b9/tests/test_cpf.py#L47-L57

**Comment by antoniamaia** [comment]
@camilamaia posso fazer? :)
