### ISSUE TITLE
Add brazilian-utils header to README.md and README_EN.md files

### ISSUE THREAD

**Issue by camilamaia** [brazilian-utils/python#12]
Add brazilian-utils header to README.md and README_EN.md files

Like this:

![image](https://user-images.githubusercontent.com/2728804/126511073-18f4d45b-9c26-4e11-b01d-e38a453f7957.png)

The same we have for JS version: https://github.com/brazilian-utils/brazilian-utils/blob/main/README.md

Code:

```html
<div align="center">
<h1>🇧🇷 Brazilian Utils</h1>

<p>Utils library for Brazilian-specific businesses.</p>
</div>
```

**Comment by antoniamaia** [comment]
@camilamaia can I take this issue? :)

**Comment by camilamaia** [comment]
Sure thing @antoniamaia!
