### ISSUE TITLE
Criar um Código de Conduta para o repositório

### ISSUE THREAD

**Issue by camilamaia** [brazilian-utils/python#130]
1. Criar um arquivo na raíz do projecto chamado `CODE_OF_CONDUCT.md`. Ele deve conter o Código de Conduta do repositório em **português**.
2. Criar um arquivo na raíz do projecto chamado `CODE_OF_CONDUCT_EN.md`. Ele deve conter o Código de Conduta do repositório em **inglês**.

Sobre Código de Conduta:
- https://opensource.guide/pt/code-of-conduct/#:~:text=Um%20código%20de%20conduta%20é,seus%20participantes%2C%20mas%20você%20mesmo.

Exemplos: 
- https://github.com/okfn-brasil/.github/blob/main/profile/CODE_OF_CONDUCT.md / https://github.com/okfn-brasil/.github/blob/4bc836cd985fcf95f9f868d79cccecc48817dcb9/profile/CODE_OF_CONDUCT-en-US.md
- https://github.com/scanapi/scanapi/blob/main/CODE_OF_CONDUCT.md
- https://www.contributor-covenant.org

**Comment by camilamaia** [comment]
@antoniamaia tais ainda fazendo esse? Ou posso pegar? 😄

**Comment by antoniamaia** [comment]
> @antoniamaia tais ainda fazendo esse? Ou posso pegar? 😄

pode sim!!

**Comment by camilamaia** [comment]
> > @antoniamaia tais ainda fazendo esse? Ou posso pegar? 😄
> 
> pode sim!!

Feito!! Valeu <3
