### ISSUE TITLE
Validar Placa de Carro - Formato Mercosul / PIV (LLLNLNN)

### ISSUE THREAD

**Issue by camilamaia** [brazilian-utils/python#175]
**Seu pedido de recurso está relacionado a um problema? Por favor, descreva.**

Verificar se uma String corresponde a uma placa de carro válida segundo o Formato Mercosul / PIV (LLLNNNN), que por definição da [RESOLUÇÃO Nº 780, DE 26 DE JUNHO DE 2019](https://www.in.gov.br/web/dou/-/resolucao-n-780-de-26-de-junho-de-2019-179414765) é o seguinte:

````
Composto de 7 (sete) caracteres alfanuméricos na sequência LLLNLNN, com combinação aleatória, distribuída e controlada pelo DENATRAN.

O caracter "L" refere-se à letra, e o caracter "N" refere-se ao numeral.
````

**Descreva a solução que você gostaria**
Chamar um novo utilitário passando uma String e receber um boolean indicando se a String é uma placa de carro válida ou não segundo o formato Mercosul / PIV. A String já deve estar sem formatação, sem símbolos.

**Descreva alternativas que você considerou**
Criar uma função genérica `is_valid_license_plate_mercosul` 

```python
def is_valid_license_plate_mercosul(license_plate):
    ...
```

Exemplo de uso:

```python
from brutils import is_valid_license_plate_mercosul

>>> is_valid_license_plate_mercosul("ABC1D23")
True
>>> is_valid_license_plate_mercosul("ABC123")
False
>>> is_valid_license_plate_mercosul("ABC-1D23")
False
>>> is_valid_license_plate_old_format("abcd123")
False
```

**Contexto adicional**
* Não é necessário validar se a placa existe de fato.
* https://pt.wikipedia.org/wiki/Placas_de_identifica%C3%A7%C3%A3o_de_ve%C3%ADculos_no_Brasil
* https://www.gov.br/transportes/pt-br/centrais-de-conteudo/resolucao-231-pdf

**Comment by magnunleno** [comment]
Oi @camilamaia, você poderia atribuir essa issue a mim? Obrigado!

**Comment by camilamaia** [comment]
@magnunleno feito!!

**Comment by magnunleno** [comment]
O Pull Request #215 com essa funcionalidade foi aceito, essa issue já pode ser encerrada. Obrigado!
