### ISSUE TITLE
Validar Placa de Carro

### ISSUE THREAD

**Issue by camilamaia** [brazilian-utils/python#176]
**Seu pedido de recurso está relacionado a um problema? Por favor, descreva.**
Verificar se uma String corresponde a uma placa de carro válida - podendo ser tanto do formato antigo (ABC-123) quanto do formato novo (padrão Mercosul)

**Descreva a solução que você gostaria**
Chamar um novo utilitário passando uma String e receber um boolean indicando se a String é uma placa de carro válida ou não.

**Descreva alternativas que você considerou**
Criar uma função genérica `is_valid_license_plate` que chama internamente as duas funções de validação de acordo com o formato:

```python
def is_valid_license_plate(license_plate):
    return is_valid_license_plate_old_format || is_valid_license_plate_mercosul_format
```

Exemplo de uso:

```python
from brutils import is_valid_license_plate

>>> is_valid_license_plate("ABC-123")
True
>>> is_valid_license_plate("ABC1D23")
True
>>> is_valid_license_plate("abcd123")
False
```

**Contexto adicional**
* Depende das issues #174 e #175
* Não é necessário validar se a placa existe de fato.
* https://pt.wikipedia.org/wiki/Placas_de_identifica%C3%A7%C3%A3o_de_ve%C3%ADculos_no_Brasil
* http://www.placnord.com.br/blog/placas-de-identificacao-de-veiculos-no-brasil

**Comment by antoniamaia** [comment]
Closed by @kaioduarte [#240](https://github.com/brazilian-utils/brutils-python/pull/240)
