### ISSUE TITLE
Verificar Formato da Placa de Carro

### ISSUE THREAD

**Issue by camilamaia** [brazilian-utils/python#178]
**Seu pedido de recurso está relacionado a um problema? Por favor, descreva.**

Dada uma String correspondente a uma placa de carro válida, retornar se o formato da placa é o antigo (LLLNNNN), ou o novo Formato Mercosul / PIV (LLLNLNN).

Definição do Formato Antigo (LLLNNNN), segundo a [RESOLUÇÃO 231 DE 15 DE MARÇO DE 2007](https://www.gov.br/transportes/pt-br/centrais-de-conteudo/resolucao-231-pdf):

````
Composto por 7 (sete) caracteres alfanuméricos individualizados sendo o primeiro grupo composto por 3
(três), resultante do arranjo, com repetição de 26 (vinte e seis) letras, tomadas três a três, e o
segundo grupo composto por 4 (quatro), resultante do arranjo, com repetição, de 10 (dez)
algarismos, tomados quatro a quatro.
````

Definição do Formato Mercosul / PIV (LLLNLNN), segundo [RESOLUÇÃO Nº 780, DE 26 DE JUNHO DE 2019](https://www.in.gov.br/web/dou/-/resolucao-n-780-de-26-de-junho-de-2019-179414765):

````
Composto de 7 (sete) caracteres alfanuméricos na sequência LLLNLNN, com combinação aleatória, distribuída e controlada pelo DENATRAN.

O caracter "L" refere-se à letra, e o caracter "N" refere-se ao numeral.
````

**Descreva a solução que você gostaria**

* Chamar um novo utilitário passando uma String correspondente a uma placa de carro válida e retornar uma string representando o seu formato: "LLLNNNN" (antigo)  ou o novo "LLLNLNN"(Formato Mercosul / PIV) .
* A String já deve estar sem formatação, sem símbolos.
* Caso a placa passada como parâmetro não seja válida nem no formato antigo nem no formato Mercosul / PIV, retornar None
* Não diferenciar entre maiúsculas e minúsculas

**Descreva alternativas que você considerou**

Criar um novo utilitário `get_license_plate_format`: 

```python
def get_license_plate_format(license_plate):
    ...
```

Exemplo de uso:

```python
from brutils import get_license_plate_format

>>> get_license_plate_format("ABC123")
"LLLNNNN"
>>> get_license_plate_format("abc123")
"LLLNNNN"
>>> get_license_plate_format("ABC1D23")
"LLLNLNN"
>>> get_license_plate_format("abc1d23")
"LLLNLNN"
>>> get_license_plate_format("ABCD123")
None
```

**Contexto adicional**

* https://pt.wikipedia.org/wiki/Placas_de_identifica%C3%A7%C3%A3o_de_ve%C3%ADculos_no_Brasil
* https://www.gov.br/transportes/pt-br/centrais-de-conteudo/resolucao-231-pdf

**Comment by pontes-guilherme** [comment]
Posso trabalhar nesse item?

**Comment by camilamaia** [comment]
@pontes-guilherme claro, feito!

**Comment by camilamaia** [comment]
Oi @kaioduarte! Já que vc abriu o PR para issue, posso te dar o assign?

**Comment by kaioduarte** [comment]
@camilamaia sim :)
