### ISSUE TITLE
Validar e-mail

### ISSUE THREAD

**Issue by antoniamaia** [brazilian-utils/python#179]
**Seu pedido de recurso está relacionado a um problema? Por favor, descreva.**
Verificar se uma string corresponde a um e-mail válido. As regras para validar um endereço de e-mail geralmente seguem as especificações definidas pelo RFC 5322 (atualizado pelo RFC 5322bis), que é o padrão amplamente aceito para formatos de endereços de e-mail. Aqui estão algumas regras gerais que você pode usar como ponto de partida:
```
1. Formato Básico: Um endereço de e-mail geralmente consiste em duas partes separadas por um "@" (arroba). A parte antes do "@" é o nome do usuário (local part), e a parte depois do "@" é o domínio (domain part).
2. Nome de Usuário: O nome de usuário pode conter letras (maiúsculas e minúsculas), números, pontos (.), hífens (-) e underscores (_). No entanto, não pode começar ou terminar com ponto e não pode conter dois pontos consecutivos.
3. Domínio: O domínio deve ter pelo menos um ponto (.), não pode começar ou terminar com ponto e não pode conter espaços em branco. Além disso, o domínio deve conter apenas letras (maiúsculas e minúsculas) e números, além de hífens (-) e pontos. 
4. Tamanho: O nome de usuário e o domínio têm limites de tamanho. O nome de usuário geralmente não deve exceder 64 caracteres, e o domínio não deve exceder 255 caracteres.
5. Validação de Formato Geral: Você pode usar expressões regulares para validar o formato geral do endereço de e-mail. 
 ```

**Descreva a solução que você gostaria**
Chamar um novo utilitário passando uma String e receber um boolean indicando se o e-mail é válido ou não.

**Descreva alternativas que você considerou**
Criar um novo utilitário `is_valid_email`.

```python 
def is_valid_email(email):
...
```  
Exemplo de uso:
```python 
from brutils import is_valid_email

>>> is_valid_email("joao.ninguem@gmail.com")
True
>>> is_valid_email(".joao.ninguem@gmail.com")
False
>>> is_valid_email("joao.ninguem@gmail.")
False
>>> is_valid_email("joao ninguem@gmail.com")
False
```  

**Contexto adicional**
Adicione qualquer outro contexto ou capturas de tela sobre o pedido de recurso aqui.
- Não é necessário validar se o e-mail existe de fato;
- https://snov.io/knowledgebase/br/como-e-um-formato-valido-de-endereco-de-email/#:~:text=Um%20endere%C3%A7o%20de%20e%2Dmail%20v%C3%A1lido%20consiste%20em%20dois%20componentes,a%20conta%20de%20e%2Dmail
- https://pt.wikipedia.org/wiki/E-mail

**Comment by Anurag-Nagpal** [comment]
Hi @antoniamaia, can I work on this? if yes you can assign this to me please.

**Comment by antoniamaia** [comment]
@Anurag-Nagpal sure!! Thanks for collaborating! 🤝

**Comment by Anurag-Nagpal** [comment]
Hi @antoniamaia , can you review this https://github.com/brazilian-utils/brutils-python/pull/213, thanks
