### ISSUE TITLE
Gerar Placa de Carro Aleatória e Válida

### ISSUE THREAD

**Issue by camilamaia** [brazilian-utils/python#181]
**Seu pedido de recurso está relacionado a um problema? Por favor, descreva.**

Conseguir gerar placas válidas de carro, podendo especificar o formato: antigo (LLLNNNN) ou o novo Formato Mercosul / PIV (LLLNLNN)

Definição do Formato Antigo (LLLNNNN), segundo a [RESOLUÇÃO 231 DE 15 DE MARÇO DE 2007](https://www.gov.br/transportes/pt-br/centrais-de-conteudo/resolucao-231-pdf):

````
Composto por 7 (sete) caracteres alfanuméricos individualizados sendo o primeiro grupo composto por 3
(três), resultante do arranjo, com repetição de 26 (vinte e seis) letras, tomadas três a três, e o
segundo grupo composto por 4 (quatro), resultante do arranjo, com repetição, de 10 (dez)
algarismos, tomados quatro a quatro.
````

Definição do Formato Mercosul / PIV (LLLNLNN), segundo [RESOLUÇÃO Nº 780, DE 26 DE JUNHO DE 2019](https://www.in.gov.br/web/dou/-/resolucao-n-780-de-26-de-junho-de-2019-179414765):

````
Composto de 7 (sete) caracteres alfanuméricos na sequência LLLNLNN, com combinação aleatória, distribuída e controlada pelo DENATRAN.

O caracter "L" refere-se à letra, e o caracter "N" refere-se ao numeral.
````

**Descreva a solução que você gostaria**

* Chamar um novo utilitário passando uma String correspondente ao formato e retornar uma String correspondendo a uma placa aleatória e válida, sem formatação.
* Formatos válidos "LLLNNNN" ou "LLLNLNN"
* O valor padrão (default) do formato deve ser o "LLLNLNN"
* Caso o formato não seja válido, retornar None
* Sempre retornar maiúsculas

**Descreva alternativas que você considerou**

Criar um novo utilitário `format_license_plate`: 

```python
def generate_license_plate(format="LLLNLNN"):
    ...
```

Exemplo de uso:

```python
from brutils import generate_license_plate

>>> generate_license_plate()
"ABC1D23"
>>> generate_license_plate(format="LLLNLNN")
"ABC4D56"
>>> generate_license_plate(format="LLLNNNN")
"ABC123"
>>> generate_license_plate(format="invalid")
None
```

**Contexto adicional**

* https://pt.wikipedia.org/wiki/Placas_de_identifica%C3%A7%C3%A3o_de_ve%C3%ADculos_no_Brasil
* https://www.gov.br/transportes/pt-br/centrais-de-conteudo/resolucao-231-pdf

**Comment by magnunleno** [comment]
Oi @camilamaia  e @antoniamaia, vocês poderiam atribuir essa issue para mim? Obrigado!

**Comment by antoniamaia** [comment]
@magnunleno bora!! 🚀
