### ISSUE TITLE
Remover Símbolos de Placa de Carro

### ISSUE THREAD

**Issue by camilamaia** [brazilian-utils/python#182]
**Seu pedido de recurso está relacionado a um problema? Por favor, descreva.**

Dada uma String correspondente a uma placa de carro, retornar uma String correspondendo a esta placa sem traço.

**Descreva a solução que você gostaria**

* Chamar um novo utilitário passando uma String correspondente a uma placa de carro e retornar essa mesma String porém sem sem traço, se tiver.
* Só deve ser removido `-`, nenhum outro símbolo

**Descreva alternativas que você considerou**

Criar um novo utilitário `remove_symbols_license_plate`: 

```python
def remove_symbols_license_plate(license_plate):
    ...
```

Exemplo de uso:

```python
from brutils import remove_symbols_license_plate

>>> remove_symbols_license_plate("ABC-123")
"ABC123"
>>> remove_symbols_license_plate("abc123")
"abc123"
>>> format_license_plate("ABCD123")
"ABCD123"
```

**Contexto adicional**

* https://pt.wikipedia.org/wiki/Placas_de_identifica%C3%A7%C3%A3o_de_ve%C3%ADculos_no_Brasil
* https://www.gov.br/transportes/pt-br/centrais-de-conteudo/resolucao-231-pdf

**Comment by pontes-guilherme** [comment]
Posso trabalhar nesse item?

**Comment by camilamaia** [comment]
@pontes-guilherme claro, feito!!
