### ISSUE TITLE
Remover Símbolos do Número de Telefone

### ISSUE THREAD

**Issue by antoniamaia** [brazilian-utils/python#187]
**Seu pedido de recurso está relacionado a um problema? Por favor, descreva.**
Remover os símbolos de uma string que contém um número de telefone brasileiro.

**Descreva a solução que você gostaria**
- Chamar um novo utilitário passando uma String com símbolos e receber a mesma String formatada, sem símbolos. 
- Devem ser retirados apenas os símbolos "padrões" `+` `" "` `(` `)` e `-`, nenhum outro símbolo.

**Descreva alternativas que você considerou**
- Criar um novo utilitário `remove_symbols_phone`:

```python
def remove_symbols_phone(phone):
...
```
Exemplo de uso:

```python

from brutils import remove_symbols_phone

>>> remove_symbols_phone("(11)99402-9275")
"11994029275"
>>> remove_symbols_phone("(16)3501-4415")
"1635014415"
```

**Contexto adicional**
- https://www.gov.br/anatel/pt-br/regulado/numeracao/plano-de-numeracao-brasileiro

**Comment by giovannism20** [comment]
Posso pegar essa @antoniamaia ?

**Comment by camilamaia** [comment]
Oii @giovannism20, posso te dar o assign para essa issue, uma vez que você já abriu o PR para ela? Só para evitar que outras pessoas a implementem também.

**Comment by giovannism20** [comment]
Sim @camilamaia
