### ISSUE TITLE
Formatar Número de Telefone

### ISSUE THREAD

**Issue by antoniamaia** [brazilian-utils/python#189]
**Seu pedido de recurso está relacionado a um problema? Por favor, descreva.**
Dada uma String correspondente a um número de telefone válido, podendo ser fixo ou móvel, retornar uma String correspondendo a este número formatada com parênteses e traço.

**Descreva a solução que você gostaria**
- Chamar um novo utilitário passando uma String correspondente a um número de telefone válido e retornar uma String correspondendo a este número formatada com parênteses (DDD) e traço.
- A String deve estar sem formatação, sem símbolos.
- Caso o número passado como parâmetro não seja válido (fixo ou móvel), retornar None

**Descreva alternativas que você considerou**
- Criar um novo utilitário format_phone:
```python
def format_phone(phone):
...
```

Exemplo de Uso:
```python
from brutils import format_phone

>>> format_phone("11994029275")
"(11)99402-9275"
>>> format_phone("1635014415")
"(16)3501-4415"
>>> format_phone("333333")
None
```
**Contexto adicional**
- (https://www.gov.br/anatel/pt-br/regulado/numeracao/plano-de-numeracao-brasileiro)

**Comment by jhonatacaiob** [comment]
Olá, caso ainda estiver aberto, gostaria de trabalhar nessa issue

**Comment by jhonatacaiob** [comment]
Solução dessa issue neste [pull request](https://github.com/brazilian-utils/brutils-python/pull/231)

**Comment by antoniamaia** [comment]
show, @jhonatacaiob, obrigada por sua contribuição!! 😄
