### ISSUE TITLE
Gerar Número de Telefone Fixo Válido e Aleatório

### ISSUE THREAD

**Issue by antoniamaia** [brazilian-utils/python#190]
**Seu pedido de recurso está relacionado a um problema? Por favor, descreva.**
Gerar um número de telefone fixo válido e aleatório

**Descreva a solução que você gostaria**
- Chamar um novo utilitário que retorna um número de telefone fixo brasileiro válido e aleatório.
- Sem formatação 

**Descreva alternativas que você considerou**
- Criar um novo utilitário `generate_landline_phone`:
```pyhton
def generate_landline_phone():
...
```

Exemplo de uso:
```pyhton
from brutils import generate_landline_phone

>>> generate_landline_phone()
"8130329450"
>>> generate_landline_phone()
"4832249009"

```
**Contexto adicional**
- https://www.gov.br/anatel/pt-br/regulado/numeracao/plano-de-numeracao-brasileiro

**Comment by MarcelFox** [comment]
Posso pega esse também?

**Comment by antoniamaia** [comment]
@MarcelFox simmm 🚀
