### ISSUE TITLE
Gerar Número de Telefone Celular Válido e Aleatório

### ISSUE THREAD

**Issue by antoniamaia** [brazilian-utils/python#191]
**Seu pedido de recurso está relacionado a um problema? Por favor, descreva.**
Gerar um número de telefone móvel válido e aleatório

**Descreva a solução que você gostaria**
- Chamar um novo utilitário que retorna um número de telefone móvel brasileiro válido e aleatório.
- Sem formatação

**Descreva alternativas que você considerou**
- Criar um novo utilitário generate_mobile_phone:

```python
def generate_mobile_phone():
...
```
Exemplo de uso:

```python
from brutils import generate_mobile_phone

>>> generate_mobile_phone()
"65992892914"
>>> generate_mobile_phone()
"9292887112"
```

**Contexto adicional**
- https://www.gov.br/anatel/pt-br/regulado/numeracao/plano-de-numeracao-brasileiro

**Comment by jhonatacaiob** [comment]
Olá @antoniamaia, poderia atribuir essa issue a mim? Obrigado!

**Comment by jhonatacaiob** [comment]
Solução dessa issue nesse [pull request](https://github.com/brazilian-utils/brutils-python/pull/232)
