### ISSUE TITLE
Remover o Código Internacional de Números de Telefone Brasileiros

### ISSUE THREAD

**Issue by antoniamaia** [brazilian-utils/python#192]
**Seu pedido de recurso está relacionado a um problema? Por favor, descreva.**
Remover o código internacional (+55) de uma string que contém um número de telefone brasileiro.

**Descreva a solução que você gostaria**
- Chamar um novo utilitário passando uma String com +55 e receber a mesma String formatada, sem o código internacional.
- Devem ser retirados apenas o número `55`, nenhum outro símbolo ou número.
- Verificar se a string recebida inicia com "55", caso não comece, retornar a mesma string.

**Descreva alternativas que você considerou**
- Criar um novo utilitário remove_international_code_phone:
```python
def remove_international_code_phone(phone):
...
```
Exemplo de uso:

```python
from brutils import remove_international_code_phone

>>> remove_international_code_phone("5511994029275")
"11994029275"
>>> remove_international_code_phone("1635014415")
"1635014415"
```
**Contexto adicional**
- (https://www.gov.br/anatel/pt-br/regulado/numeracao/plano-de-numeracao-brasileiro)

**Comment by KauanAmarante** [comment]
Hey, tudo bem?
Posso puxar o desenvolvimento dessa issue?

**Comment by antoniamaia** [comment]
@KauanAmarante opa, pode sim! vou te dar o assign 😄

**Comment by antoniamaia** [comment]
@KauanAmarante Fizemos algumas mudanças na descrição da sua issue, pois avaliamos que outra função poderia fazer a retirada do símbolo, agora sua função somente retira o "55". Dá um toque se não ficou claro! 😄

**Comment by KauanAmarante** [comment]
Combinado!

**Comment by antoniamaia** [comment]
oii sumido! rs @KauanAmarante, vais continuar trabalhando nessa issue? 😇

**Comment by joseevilasio** [comment]
Olá, ainda precisa de ajuda nessa feat ? Estou disponível para ajudar nessa ou em outra se for o caso. 😎

**Comment by guirisouza** [comment]
@antoniamaia conseguiram andar com essa issue? Estou disponível para contribuir

**Comment by antoniamaia** [comment]
@joseevilasio e @guirisouza desculpa a demora, mês corrido pra gente por aqui! algum dos dois ainda disponível para ajudar? 😅

**Comment by joseevilasio** [comment]
> @joseevilasio e @guirisouza desculpa a demora, mês corrido pra gente por aqui! algum dos dois ainda disponível para ajudar? 😅

Estou disponível! 😄
