### ISSUE TITLE
Remover Símbolos do PIS

### ISSUE THREAD

**Issue by antoniamaia** [brazilian-utils/python#205]
**Seu pedido de recurso está relacionado a um problema? Por favor, descreva.**
Remover os símbolos de uma String que contém um número de PIS.

**Descreva a solução que você gostaria**
- Chamar um novo utilitário passando uma String com símbolos e receber a mesma String formatada, sem símbolos.
- Devem ser retirados apenas os símbolos "padrões" `.` e `-`, nenhum outro símbolo.

**Descreva alternativas que você considerou**
- Criar um novo utilitário remove_symbols_pis:
```pyhton
def remove_symbols_pis(pis):
...
```
Exemplo de uso:
```
from brutils import remove_symbols_pis

>>> remove_symbols_pis("120.64634.51-9")
"12064634519"
>>> remove_symbols_pis("170.33259.50-4")
"17033259504"
```

**Contexto adicional**
- https://pt.wikipedia.org/wiki/PIS/PASEP
- https://www.macoratti.net/alg_pis.htm

**Comment by pontes-guilherme** [comment]
Posso trabalhar nesse item?
