### ISSUE TITLE
Formatar número do PIS

### ISSUE THREAD

**Issue by antoniamaia** [brazilian-utils/python#206]
**Seu pedido de recurso está relacionado a um problema? Por favor, descreva.**
Dada uma String correspondente a um número de PIS válido, retornar uma String correspondendo a este número formatada com pontos e traço. 
```
NNN.NNNNN.NN-D
```

**Descreva a solução que você gostaria**
- Chamar um novo utilitário passando uma String correspondente a um número de PIS válido e retornar uma String correspondendo a este número formatada com pontos e traço.
- A String deve estar sem formatação, sem símbolos.
- Caso o número passado como parâmetro não seja válido, retornar None

**Descreva alternativas que você considerou**
- Criar um novo utilitário format_pis:

```python
def format_pis(pis):
...
```
Exemplo de Uso:
```
from brutils import format_pis

>>> format_pis("12064634519")
"120.64634.51-9"
>>> format_pis("17033259504")
"170.33259.50-4"
>>> format_pis("333333")
None
```
**Contexto adicional**

- https://pt.wikipedia.org/wiki/PIS/PASEP
- https://www.macoratti.net/alg_pis.htm

**Comment by patricia-salles** [comment]
Olá, posso contribuir nessa issue?

**Comment by camilamaia** [comment]
@patricia-salles claro! Tá na mão!

**Comment by patricia-salles** [comment]
Olá @camilamaia eu inclui a issue 206, mas está com algum erro nas validações do git. Tentei corrigir, mas não consegui, é a primeira vez que estou fazendo uma contribuição no git e devo estar fazendo algo de errado. Sabe o que pode ser?

**Comment by antoniamaia** [comment]
@patricia-salles já te dou um retorno ali no PR :)

**Comment by camilamaia** [comment]
Essa já foi feita no PR #224 💪
