### ISSUE TITLE
Validar o número de um Processo Jurídico

### ISSUE THREAD

**Issue by antoniamaia** [brazilian-utils/python#207]
**Seu pedido de recurso está relacionado a um problema? Por favor, descreva.**
Verificar se uma String corresponde a um número de Processo Jurídico válido, conforme as regras da numeração.

**Descreva a solução que você gostaria**
- Chamar um novo utilitário passando uma String e receber um boolean indicando se a String é um número de Processo Jurídico válido ou não.
- Recebe uma string sem formatação.
```
O número do processo jurídico é composto por 20 caracteres numéricos no formato NNNNNNN-DD.AAAA.J.TR.0000, e esta formatação se dá com base na Resolução 65 de 16 de Dezembro 2008, que instituiu a numeração única de processos no âmbito do Poder Judiciário, composta de 6 campos obrigatórios.

NNNNNNN: com 7 dígitios, identifica o número sequencial do processo por unidade de origem (0000), a ser reiniciado a cada ano.

DD: com 2 dígitos, se refere ao código verificador, cujo cálculo deve ser efetuado pela aplicação do algoritmo Módulo 97 Base 10, conforme Norma ISO 7064:2003.

AAAA: com 4 dígitos, identifica o ano de ajuizamento.

J: com 1 dígito, identifica o órgão ou segmento do Poder Judiciário: (1) STF, (2) CNJ, (3) STJ, (4) Justiça Federal, (5) Justiça do Trabalho, (6) Justiça Eleitoral, (7) Justiça Militar da União, (8) Justiça dos Estados e do Distrito Federal e Territórios, (9) Justiça Militar Estadual.

TR: com 2 dígitos, identifica o Tribunal do respectivo órgão.

0000: com 4 dígitos, identifica a unidade/vara de origem.
```

**Descreva alternativas que você considerou**
- Criar um novo utilitário is_valid_processo_juridico

```pyhton
def is_valid_processo_juridico(numero_processo):
...
```
Exemplo de uso:

```python
from brutils import is_valid_processo_juridico

>>> is_valid_processo_juridico("57273655020238000864")
True
>>> is_valid_processo_juridico("18083077920234004451")
True
>>> is_valid_processo_juridico("590892361")
False
>>> is_valid_processo_juridico("59089239020232004321")
False
```

**Contexto adicional**
- Não é necessário verificar se o Processo Jurídico existe de fato;
- https://btcreditos.com.br/blog/numero-cnj-o-que-e-a-numeracao-unica-de-processo/#:~:text=A%20estrutura%20da%20numera%C3%A7%C3%A3o%20%C3%BAnica%20de%20processo%20%C3%A9%20formada%20por,respectivo%20segmento%20ou%20circunscri%C3%A7%C3%A3o%20judici%C3%A1ria;
- https://forum.abj.org.br/t/numero-do-processo-cnj/133;

**Comment by MarcelFox** [comment]
Também tô fazendo essa aqui, pergunta @antoniamaia é necessário validar se o órgão juridico, o tribunal e a origem batem correto? Ou seja, para criar um número de processo a origem tem que bater com o tribunal e o órgão jurídico, certo?

**Comment by antoniamaia** [comment]
@MarcelFox eita!! perdão, achei que tinha te respondido, mas foi só na minha cabeça 😵‍💫 Se quiseres continuar com essa issue, já te dei o assign! Sobre a tua pergunta como não fazemos a validação se realmente existe o número, podes fazer da forma mais simples.. masss se conseguires topar o desafio de relacionar e de fato fazer esta verificação, fica a teu critério!! :)

**Comment by MarcelFox** [comment]
Ah tranquilo! No PR da issue #208 enviei um dict que faz a relação do processo jurídico, acho que a validação vai ficar correta com esse dict.
