### ISSUE TITLE
Gerar um número Válido e Aleatório de Processo Jurídico

### ISSUE THREAD

**Issue by antoniamaia** [brazilian-utils/python#208]
**Seu pedido de recurso está relacionado a um problema? Por favor, descreva.**
Desejamos adicionar um novo utilitário à nossa biblioteca que permita aos usuários gerar números de Processo Jurídico válidos e aleatórios, onde eles possam escolher o ano do ajuizamento e/ou o órgão da justiça. 

**Descreva a solução que você gostaria**
- Chamar um novo utilitário passando opções para o ano de ajuizamento e/ou o órgão/segmento da justiça e receber um número de Processo Jurídico válido e aleatório.

```
O número do processo jurídico deve ser composto por 20 caracteres numéricos no formato NNNNNNN-DD.AAAA.J.TR.0000, conforme a Resolução 65 de 16 de Dezembro de 2008.
- NNNNNNN é um número sequencial do processo por unidade de origem (0000), reiniciado a cada ano.
- DD é um código verificador calculado pelo algoritmo Módulo 97 Base 10.
- AAAA identifica o ano de ajuizamento.
- J identifica o órgão ou segmento do Poder Judiciário.
- TR identifica o Tribunal do respectivo órgão.
- 0000 identifica a unidade/vara de origem.
```

**Descreva alternativas que você considerou**
O utilitário deve aceitar as seguintes opções:
- Ano: O ano de ajuizamento desejado. O padrão é 2023 se não for especificado.
- Órgão: O órgão/segmento da justiça desejado. Se não for especificado, um órgão/segmento aleatório deve ser escolhido.

- Criar um novo utilitário `generate_processo_juridico`:
```python
def generate_processo_juridico(ano,orgao):
 ...
```

Exemplo de uso
```pyhton
from brutils import generate_processo_juridico

>>> generate_processo_juridico()
"57273655020238000864"  # Ano 2023, órgão aleatório
>>> generate_processo_juridico(ano=2025)
"18083077920234004451"  # Ano 2025, órgão aleatório
>>> generate_processo_juridico(orgao=5)
"59089239020232004321"  # Ano 2023, Justiça do Trabalho
>>> generate_processo_juridico(ano=2024, orgao=4)
"49083276120243005678"  # Ano 2024, Justiça Federal

```
**Contexto adicional**

- Não é necessário verificar se o Processo Jurídico gerado existe de fato.
- Referências úteis:
[Estrutura da numeração única de processo](https://btcreditos.com.br/blog/numero-cnj-o-que-e-a-numeracao-unica-de-processo/#:~:text=A%20estrutura%20da%20numera%C3%A7%C3%A3o%20%C3%BAnica%20de%20processo%20%C3%A9%20formada%20por,respectivo%20segmento%20ou%20circunscri%C3%A7%C3%A3o%20judici%C3%A1ria)
[Fórum ABJ sobre número do processo CNJ](https://forum.abj.org.br/t/numero-do-processo-cnj/133)

**Comment by MarcelFox** [comment]
Também tô fazendo essa hahaha, na verdade tava fazendo tudo já inclusive a regra
