### ISSUE TITLE
Remover símbolos do número do Processo Jurídico

### ISSUE THREAD

**Issue by antoniamaia** [brazilian-utils/python#209]
**Seu pedido de recurso está relacionado a um problema? Por favor, descreva.**
Remover os símbolos de uma String que contém um número de um Processo Jurídico.

**Descreva a solução que você gostaria**
- Chamar um novo utilitário passando uma String com símbolos e receber a mesma String formatada, sem símbolos.
- Devem ser retirados apenas os símbolos "padrões": `-` e `.`, nenhum outro símbolo.

**Descreva alternativas que você considerou**
Criar um novo utilitário `remove_symbols_processo_juridico`:
```phyton
def remove_symbols_processo_juridico(processo_juridico):
...
```
Exemplo de uso:
```python
from brutils import remove_symbols_processo_juridico

>>> remove_symbols_processo_juridico("6439067-89.2023.4.04.5902")
"64390678920234045902"
>>> remove_symbols_processo_juridico("4976023-82.2012.7.00.2263")
"49760238220127002263"
```
**Contexto adicional**
Referências úteis:
[Estrutura da numeração única de processo](https://btcreditos.com.br/blog/numero-cnj-o-que-e-a-numeracao-unica-de-processo/#:~:text=A%20estrutura%20da%20numera%C3%A7%C3%A3o%20%C3%BAnica%20de%20processo%20%C3%A9%20formada%20por,respectivo%20segmento%20ou%20circunscri%C3%A7%C3%A3o%20judici%C3%A1ria)
[Fórum ABJ sobre número do processo CNJ](https://forum.abj.org.br/t/numero-do-processo-cnj/133)

**Comment by pontes-guilherme** [comment]
Posso trabalhar nesse item?

**Comment by antoniamaia** [comment]
Oii @pontes-guilherme, vi que você já esta assigned em outras duas issues.. Vou aguardar seus PRs, assim podemos permitir que outras pessoas também tenham a oportunidade de colaborar e evita que recursos fiquem inativos por muito tempo, ok?
espero que nos entenda 😄 🙈 Obrigada por sua colaboração!!

**Comment by pontes-guilherme** [comment]
Claro, sem problemas. Na verdade essa foi a primeira issue que eu vi e acabei fazendo o setup local do projeto, me empolguei e desenvolvi a feature antes de pedir pra ser atribuída :sweat_smile: , só faltou mandar PR. Mas eu vou tentar mandar as outras duas ainda hoje

**Comment by antoniamaia** [comment]
@guilhermecomum oba!! queis que eu troque?

**Comment by pontes-guilherme** [comment]
@antoniamaia pode ser então. Pode trocar por qualquer uma das outras que atribuíram :)
