### ISSUE TITLE
Formatar o número do Processo Jurídico

### ISSUE THREAD

**Issue by antoniamaia** [brazilian-utils/python#210]
**Seu pedido de recurso está relacionado a um problema? Por favor, descreva.**
Dada uma String correspondente a um número de Processo Jurídico válido, retornar uma String correspondendo a este número formatada com traço e pontos.

```
NNNNNNN-DD.AAAA.J.TR.0000
```

**Descreva a solução que você gostaria**
- Chamar um novo utilitário passando uma String correspondente a um número de Processo Jurídico válido e retornar uma String correspondendo a este número formatada com traço e pontos.
- A String deve estar sem formatação, sem símbolos.
- Caso o número passado como parâmetro não seja válido, retornar None.

**Descreva alternativas que você considerou**
- Criar um novo utilitário `format_processo_juridico`:
```python
def format_processo_juridico(processo_juridico):
...
```
Exemplo de Uso:
```python
from brutils import format_processo_juridico

>>> format_processo_juridico("43414808720123008584")
"4341480-87.2012.3.00.8584"
>>> format_processo_juridico("16198256620197006253")
"1619825-66.2019.7.00.6253"
>>> format_processo_juridico("07799120166000729")
None
```
**Contexto adicional**
Referências úteis:
[Estrutura da numeração única de processo](https://btcreditos.com.br/blog/numero-cnj-o-que-e-a-numeracao-unica-de-processo/#:~:text=A%20estrutura%20da%20numera%C3%A7%C3%A3o%20%C3%BAnica%20de%20processo%20%C3%A9%20formada%20por,respectivo%20segmento%20ou%20circunscri%C3%A7%C3%A3o%20judici%C3%A1ria)
[Fórum ABJ sobre número do processo CNJ](https://forum.abj.org.br/t/numero-do-processo-cnj/133)

**Comment by MarcelFox** [comment]
@antoniamaia é bem recente essa issue então, posso tentar pegar essa feature?

**Comment by camilamaia** [comment]
@MarcelFox claro, vai que é teu!

**Comment by MarcelFox** [comment]
pessoal acabei fazendo também a issue #209 pois fazia sentido

**Comment by antoniamaia** [comment]
@MarcelFox ficamos muito felizes em saber que nosso repo te deixou empolgado!! 🚀 massss a issue #209 já tem outro colaborador assigned! se quiseres pegar outra deste mesmo utilitário (ou outros) fique à vontade, só comentar na Issue que te dou o assign para seguires com o PR :)

**Comment by MarcelFox** [comment]
vou removar o que foi feito do 209 do PR

**Comment by MarcelFox** [comment]
@antoniamaia resolvidas as questões no PR, só não dei _resolve conversation_ pra você analisar e fechar, qualquer coisa só falar e muito obrigado pela review!
