### ISSUE TITLE
Implementar utilitário para capitalização de strings em Python

### ISSUE THREAD

**Issue by antoniamaia** [brazilian-utils/python#211]
**Seu pedido de recurso está relacionado a um problema? Por favor, descreva.**
Desejamos adicionar um novo utilitário à nossa biblioteca em Python que permita a capitalização de strings de acordo com regras específicas. A capitalização envolve a transformação da primeira letra de cada palavra em maiúscula e o restante das letras em minúscula. No entanto, queremos oferecer a capacidade de personalizar essa capitalização para manter certas palavras em letras maiúsculas ou minúsculas, de acordo com as regras estabelecidas.

**Descreva a solução que você gostaria**
- Criar uma função chamada `capitalize` que aceite uma string como entrada e opções para personalizar a capitalização. As opções podem incluir:

1. lower_case_words (lista de strings): Uma lista de palavras que devem ser mantidas em letras minúsculas, mesmo que apareçam no meio da string. Exemplo: Preposições
2. upper_case_words (lista de strings): Uma lista de palavras que devem ser mantidas em letras maiúsculas. Exemplo: Acrônimos
```
- A função capitalize_string deve operar da seguinte forma:

1. Divide a string de entrada em palavras, usando um espaço em branco como separador.
2. Filtra as palavras resultantes para remover palavras vazias ou nulas.
3. Itera sobre as palavras e, para cada palavra:
4. Converte a palavra em letras minúsculas.
5. Verifica se a palavra está na lista lower_case_words. Se estiver, mantém a palavra em letras minúsculas.
6. Verifica se a palavra está na lista upper_case_words. Se estiver, mantém a palavra em letras maiúsculas.
7. Caso contrário, torna a primeira letra da palavra maiúscula e o restante da palavra em letras minúsculas.
8. Junta as palavras novamente em uma única string, separadas por espaços, e retorna a string capitalizada.
```

**Descreva alternativas que você considerou**
- Criar um novo utilitário `capitalize`:
```python
def capitalize(string):
...
```
Exemplo de Uso:
```python
from brutils import capitalize

>>> capitalize_string("exemplo DE string")
"Exemplo de String"
>>> capitalize_string("exemplo DE String", lower_case_words=["de"])
"Exemplo de String"
>>> capitalize_string("exemplo de String", upper_case_words=["exemplo"])
"EXEMPLO de String"
```
**Contexto adicional**

**Comment by camilamaia** [comment]
Pensando aqui, acho que essa o próprio Python já cobre bem. Porque temos:

- capitalize(): para transformar a primeira letra maiúscula https://www.w3schools.com/python/ref_string_capitalize.asp
- title(): para transformar a primeira letra de cada palavra maiúscula https://www.w3schools.com/python/ref_string_title.asp
- upper(): para transformar tudo em maiúscula https://www.w3schools.com/python/ref_string_upper.asp
- lower(): para transforma tudo em minúscula https://www.w3schools.com/python/ref_string_lower.asp

Não sei bem ao certo o motivo de terem criado esse utilitário no brutils js, mas acho que em Python não precisaria.

O quê você acha @antoniamaia ?

**Comment by antoniamaia** [comment]
Beleuza!!
