### ISSUE TITLE
Validar o número de um Título Eleitoral brasileiro

### ISSUE THREAD

**Issue by antoniamaia** [brazilian-utils/python#219]
**Seu pedido de recurso está relacionado a um problema? Por favor, descreva.**
Verificar se uma String corresponde a um número de Título Eleitoral válido, conforme as regras da numeração.

**Descreva a solução que você gostaria**
- Chamar um novo utilitário passando uma String e receber um boolean indicando se a String é um número de Título Eleitoral válido ou não.
- Recebe uma string não formatada (sem espaços)

```
- O número de Inscrição do Título Eleitoral, em geral, possui doze dígitos.
- Os oito primeiros dígitos correspondem ao número sequencial.
- O nono e o décimo dígitos correspondem à Unidade Federativa (UF) à qual o eleitor pertence. Se o título não for expedido no Brasil, considera-se que a sigla da UF é 28 (ZZ).
- Os dois últimos dígitos correspondem aos Dígitos Verificadores (DV’s).
```

**Descreva alternativas que você considerou**
- Criar um novo utilitário `is_valid_titulo_eleitoral`
```python
def is_valid_titulo_eleitoral(numero_titulo):
...
```
Exemplo de uso:
```python
from brutils import is_valid_titulo_eleitoral

>>> is_valid_titulo_eleitoral("217633460930")
True
>>> is_valid_titulo_eleitoral("348833812046")
True
>>> is_valid_titulo_eleitoral("348833812000")
False
>>> is_valid_titulo_eleitoral("217633")
False
```
**Contexto adicional**
- Não é necessário verificar se o Título Eleitoral existe de fato;
- https://pt.wikipedia.org/wiki/T%C3%ADtulo_de_eleitor#:~:text=C%C3%A1lculo%20do%20d%C3%ADgito%20verificador,-Para%20realizar%20o&text=Se%20o%20t%C3%ADtulo%20eleitoral%20n%C3%A3o,d%C3%ADgitos%20correspondem%20ao%20n%C3%BAmero%20sequencial.
- http://clubes.obmep.org.br/blog/a-matematica-nos-documentos-titulo-de-eleitor/

**Comment by VPeron** [comment]
ola @antoniamaia,
gostaria de trabalhar neste item, se ainda esta de fato aberto.
pode ser?

**Comment by antoniamaia** [comment]
opa!! @VPeron claro, já vou te dar o assign! :)
