### ISSUE TITLE
Formatar o número do Título Eleitoral 

### ISSUE THREAD

**Issue by antoniamaia** [brazilian-utils/python#221]
**Seu pedido de recurso está relacionado a um problema? Por favor, descreva.**
Dada uma String correspondente a um número de Título Eleitoral  válido, retornar uma String correspondendo a este número formatada com os devidos espaços.
```
NNNN NNNN EE DD
```

**Descreva a solução que você gostaria**
- Chamar um novo utilitário passando uma String correspondente a um número de Título Eleitoral válido e retornar uma String correspondendo a este número formatada com espaços.
- A String deve estar sem formatação, sem símbolos.
- Caso o número passado como parâmetro não seja válido, retornar None.

**Descreva alternativas que você considerou**
- Criar um novo utilitário `format_titulo_eleitoral`:
```python
def format_titulo_eleitoral(numero_titulo):
...
```
Exemplo de Uso:
```python
from brutils import format_titulo_eleitoral

>>> format_titulo_eleitoral("017746811074")
"0177 4681 10 74"
>>> format_titulo_eleitoral("117351120817")
"1173 5112 08 17"
>>> format_titulo_eleitoral("6455327")
None
```

**Contexto adicional**
-https://pt.wikipedia.org/wiki/T%C3%ADtulo_de_eleitor#:~:text=C%C3%A1lculo%20do%20d%C3%ADgito%20verificador,-Para%20realizar%20o&text=Se%20o%20t%C3%ADtulo%20eleitoral%20n%C3%A3o,d%C3%ADgitos%20correspondem%20ao%20n%C3%BAmero%20sequencial.
- http://clubes.obmep.org.br/blog/a-matematica-nos-documentos-titulo-de-eleitor/

**Comment by MattheusHenrique** [comment]
Oi @antoniamaia, gostaria de trabalhar nessa issue. Pode ser?

**Comment by bermr** [comment]
Olá, gostaria de trabalhar nessa issue

**Comment by antoniamaia** [comment]
massa, @bermr! já vou te dar o assign!! :)

**Comment by bermr** [comment]
PR: https://github.com/brazilian-utils/brutils-python/pull/247
