### ISSUE TITLE
Trocar o tipo de git hook utilizado para formatação de código

### ISSUE THREAD

**Issue by camilamaia** [brazilian-utils/python#288]
## Contexto

Atualmente o projeto utiliza o hook de _pre-commit_ para formatar o código. Embora a formatação e padronização do código seja necessária e útil no projeto, executar isso a cada _commit_ me parece desnecessário, até atrapalha em certo ponto (para aqueles que gostam de dividir cada commit, deixando explicito o que foi modificado a cada mudança).

## Proposta

Podemos mudar o hook de  _pre-commit_ para um _pre-push hook_. Assim o código de formatação será verificado apenas antes do push _(possivelmente deixando um último commit de linter, sempre que o desenvolvimento for finalizado)_

_Originally posted by @MarcelFox in https://github.com/brazilian-utils/brutils-python/discussions/258_

**Comment by camilamaia** [comment]
@MarcelFox vou te adicionar a essa issue então, beleza?

**Comment by MarcelFox** [comment]
beleza
