### ISSUE TITLE
Obter endereço a partir de um cep

### ISSUE THREAD

**Issue by agaragon** [brazilian-utils/python#353]
**Seu pedido de recurso está relacionado a um problema? Por favor, descreva.**
Uma descrição clara e concisa do que é o problema. Por exemplo: "Fico sempre frustrado quando que toda a vez que vou fazer uma api que tem que buscar os dados do `viacep` no backend, tenho que fazer uma implementação nova. Idealmente eu poderia criar uma lib para compartilhar entre projetos, contudo, acho que a lib do brutils-python seria um bom lugar para adicionar essa funcioalidade também."

**Comment by leowebc** [comment]
Ao utilizar `from brutils import generate_cep` está retornando CEP invalido. 

Obrigado.

**Comment by LucasAmerico0101** [comment]
Posso trabalhar nela?

**Comment by vmagueta** [comment]
Essa issue ainda precisa ser resolvida?

**Comment by antoniamaia** [comment]
@LucasAmerico0101 e @vmagueta adoramos novas colaborações, mas esta issue está sendo resolvida pelo @gtkacz, inclusive vou dar o assign pra ele aqui! Se tiverem alguma sugestão ou puderem aguardar um pouco, logo criaremos mais issues ⭐ Obrigada pela cooperação!

**Comment by antoniamaia** [comment]
> Ao utilizar `from brutils import generate_cep` está retornando CEP invalido.
> 
> Obrigado.

@leowebc tentei replicar aqui, mas não obtive problemas. Foi na biblioteca ou no PR? consegue me dar mais infos?
Obrigada pelo feedback, novas pessoas colaboradoras são sempre bem-vindas! 🤩
