### ISSUE TITLE
Atualizar versão em inglês do arquivo de contribuição 

### ISSUE THREAD

**Issue by camilamaia** [brazilian-utils/python#391]
**Seu pedido de recurso está relacionado a um problema? Por favor, descreva.**
A [versão em português do arquivo de contribuição](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md) foi atualizada nos PRs [390][pr-390] e [401][pr-401], porém a [versão em inglês](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING_EN.md) ainda não foi.

**Descreva a solução que você gostaria**
Atualizar a [versão em inglês do arquivo de contribuição](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING_EN.md) para refletir as mudanças feitas na versão em Português nos PRs [390][pr-390] e [401][pr-401]

**Descreva alternativas que você considerou**
1. Seguir até o passo 8 do [guia de contribuição][guia-de-contribuição]

1. Como parte do passo 8, editar o arquivo https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING_EN.md, o atualizando com as mudanças correspondentes aos PRs [390][pr-390] e [401][pr-401]. Fique à vontade para utilizar ferramentas como Google Tradutor ou ChatGPT caso precise. Iremos sugerir mudanças na tradução se necessário, então não se preocupe com possíveis erros de inglês.

1. Seguir os passos seguintes do [guia de contribuição][guia-de-contribuição]

**Contexto adicional**
- https://github.com/brazilian-utils/brutils-python/issues/386
- https://github.com/brazilian-utils/brutils-python/issues/400
- A seção sobre o Changelog foi uma tradução e adaptação desta documentação: https://github.com/scanapi/scanapi/wiki/Changelog

[pr-390]: https://github.com/brazilian-utils/brutils-python/pull/390
[pr-401]: https://github.com/brazilian-utils/brutils-python/pull/401
[guia-de-contribuição]: https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#primeira-contribui%C3%A7%C3%A3o

**Comment by laistdomiciano** [comment]
bora!
