### ISSUE TITLE
Ajuste no processo de instalação

### ISSUE THREAD

**Issue by FSBEZERRA** [brazilian-utils/python#407]
**Seu pedido de recurso está relacionado a um problema? Por favor, descreva.**
Adicionar uma descrição ao processo de instalação atual utilizando somente o pip em modo dev .

**Descreva a solução que você gostaria**
Adicionar alternativa de instalação utilizando `pip install .`

**Descreva alternativas que você considerou**
Utilização do pip em modo dev, aproveitando as definições encontradas no arquivo pyproject.toml

**Contexto adicional**
Foram encontradas dificuldades utilizando o Poetry

**Comment by melissawm** [comment]
bora!

**Comment by antoniamaia** [comment]
bora!

**Comment by FloraSauerbronn** [comment]
Esse aqui esta parado @camilamaia e @antoniamaia  ? Vi que vocês retiraram algumas pessoas do assignment

**Comment by antoniamaia** [comment]
Oii, @FloraSauerbronn, acabei de dar o Assign pra ti! A tarefa envolve adicionar uma 2ª alternativa de instalação do projeto usando `pip` ao invés de `Poetry`. Atualmente, o processo de instalação usa o Poetry, mas muitas pessoas podem preferir usar pip. A ideia é documentar como instalar o projeto em modo de desenvolvimento com pip e suas dependências, baseando-se no arquivo `pyproject.toml`. Isso exige apenas um ajuste no `CONTRIBUTING.md` e `CONTRIBUTING_EN.md` para incluir os passos necessários, sem alterar o código-fonte ou o pyproject.toml.

**Comment by FloraSauerbronn** [comment]
@antoniamaia então eu só complemento o tópico 7 com essas informações ou você prefere que eu crie um tópico novo nos mds ?

**Comment by FloraSauerbronn** [comment]
@antoniamaia acredito não seja possível instalar as dependencias dev com pip utilizando o pyproject.toml
Pois pip não é um gerenciador de projetos, somente um instalador (foi o que encontrei aqui na minha pesquisa tentando entender).
A solução que teria seria criar um requirements-dev.txt com

```
ruff>=0.5.0,<0.7.0
coverage>=7.2.7
```

Vou enviar um PR.
