### ISSUE TITLE
Adicionar condição de OS no MakeFile

### ISSUE THREAD

**Issue by BeneBr** [brazilian-utils/python#414]
**Descrição do problema**
Makefile do projeto suporta apenas a execução do script no sistema operacional linux. Dessa forma, ao executar o make install em um ambiente Windows, o mesmo não irá reconhecer o comando ```chmod -R +x .githooks```, a menos é claro, que tenha o susbsistema linux instalado no OS Windows, mas creio que não deve ser levado isso em conta.

**Para Reproduzir**
Passos para reproduzir o comportamento:
Basta seguir os passos descritos aqui: https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#7-execute-o-brutils-localmente

e executar o ```make shell```. Um erro irá aparecer pois o comando ```chmod``` não existe no Windows.
 
**Comportamento esperado**
Criar o environment de forma correta, sem precisar instalar um subsistema linus em OS Windows.

**Desktop (por favor, forneça as seguintes informações):**
 - Sistema Operacional: Windows 11
 - Versão do brutils: v2.2.0

**Contexto adicional**
Aqui já tem uma forma bem simples que resolve o problema relatado:

Modificação no Makefile

```Makefile
install:
	git config --local core.hooksPath .githooks/
ifneq ($(OS),Windows_NT)
	chmod -R +x .githooks
endif
       @poetry install
```

**Comment by vianaz** [comment]
bora

**Comment by vianaz** [comment]
bora!
