### ISSUE TITLE
Implementar uma função para gerar CPF válido aleatório

### ISSUE THREAD

**Issue by pedrohdea** [brazilian-utils/python#438]
# Implementação da Função para Gerar CPF Válido Aleatório

## Descrição
Criar uma função `generate_cpf` que gera uma string de dígitos de CPF válida aleatória. A função deve retornar um CPF sem símbolos (`.` ou `-`), apenas os números.

## Especificações da Função
- **Nome da função:** `generate_cpf`
- **Entrada:** Nenhuma
- **Saída:** `str` - Um CPF válido gerado aleatoriamente.
- **Detalhes:** Não implementar a lógica da função. Apenas adicionar a docstring e um comentário `# implementar a lógica da função aqui`.

## Exemplo de Uso

```python
>>> from brutils import generate_cpf
>>> generate_cpf()
'17433964657'
>>> generate_cpf()
"10895948109"

**Comment by FabioCruzDev** [comment]
Opa boa noite,

A função já existe [generate](https://github.com/brazilian-utils/brutils-python/blob/4af1cdc2616f33b654053eadeaa689a807d1443d/brutils/cpf.py#L167)

**Comment by pedro-beemon** [comment]
Certo.

**Comment by pedrohdea** [comment]
A função já existe [generate](https://github.com/brazilian-utils/brutils-python/blob/4af1cdc2616f33b654053eadeaa689a807d1443d/brutils/cpf.py#L167)
