### ISSUE TITLE
Atualizar arquivos de Contribuição

### ISSUE THREAD

**Issue by camilamaia** [brazilian-utils/python#86]
- Renomear o arquivo https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md para https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING_EN.md
- Criar um arquivo https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md com o conteúdo em português
- Adicionar uma seção de contribuição como [essa](https://github.com/scanapi/scanapi#contributing) no README.md e README_EN.md

**Comment by antoniamaia** [comment]
Can I take this issue? :)
